openapi: 3.0.0
info:
  title: VA Notify API Documentation
  description: "This documents the API schemas for consumption by internal VA developers.<br />
  <h1>Authorisation header</h1>
  <p>You must include an authorisation header that is encoded using JSON Web Tokens.
  JSON Web Tokens have a standard header and a payload. The header consists of:
  <pre><code>
  {\n
  &nbsp;&nbsp;&nbsp;&nbsp;&quot;type&quot;: &quot;JWT&quot;,\n
  &nbsp;&nbsp;&nbsp;&nbsp;&quot;alg&quot;: &quot;HS256&quot;\n
  &nbsp;}
  </code></pre>
  </p>
  <p>
  The payload consists of:
  <pre><code>
  {\n
  &nbsp;&nbsp;&nbsp;&nbsp;&quot;iss&quot;: &quot;26785a09-ab16-4eb0-8407-a37497a57506&quot;,\n
  &nbsp;&nbsp;&nbsp;&nbsp;&quot;iat&quot;: 1568818578\n
  &nbsp;}
  </code></pre>
  </p>
  <p>
    Refer to the <a href='https://jwt.io/' target='_blank'>JSON Web Tokens website</a> for more information
    on encoding your authorisation header.
  </p>
  "
  version: 1.0.0
  contact:
    name: VA Notify team
servers:
  - url: '{protocol}://{environment}.twnotify.com'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        enum:
          - staging.api
          - dev.api
          - api
        default: api
paths:
  /organisations:
    get:
      summary: Get list of all organisations
      tags:
        - organisation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organisation'
    post:
      summary: Create an organisation
      tags:
        - organisation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                active:
                  nullable: true
                  type: boolean
                crown:
                  nullable: false
                  type: boolean
                name:
                  nullable: false
                  type: string
                organisation_type:
                  type: string
                  enum:
                    - other
              required:
                - active
                - crown
                - name
                - organisation_type
              type: object
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganisationResponse'
  /organisations/{organisation_id}/:
    get:
      summary: Find organisation by id
      tags:
        - organisation
      parameters:
        - in: path
          name: organisation_id
          schema:
            type: string
            format: uuid
          required: true
          allowEmptyValue: false
          description: Organisation identifier
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organisation'
    post:
      summary: Update an organization
      tags:
        - organisation
      parameters:
        - in: path
          name: organisation_id
          schema:
            type: string
            format: uuid
          required: true
          allowEmptyValue: false
          description: Organization identifier
      requestBody:
        description: Include values in the request body to update them
        required: true
        content:
          application/json:
            schema:
              properties:
                active:
                  nullable: true
                  type: boolean
                crown:
                  nullable: true
                  type: boolean
                name:
                  nullable: true
                  type: string
                organisation_type:
                  nullable: false
                  type: string
                  enum:
                    - other
      responses:
        204:
          description: OK
        404:
          description: Organisation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /user:
    post:
      summary: Create a user
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/User'
    get:
      summary: Get a list of all users
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
  /user/{user_id}:
    post:
      summary: Update a user
      tags:
        - user
      parameters:
        - in: path
          name: 'user_id'
          schema:
            type: integer
            format: uuid
          required: true
          allowEmptyValue: false
          description: User identifier
      requestBody:
        description: Include values in the request body to update them
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  nullable: false
                email_address:
                  type: string
                  nullable: false
                mobile_number:
                  type: string
                  nullable: false
                  example: "+19876543210"
                auth_type:
                  type: string
                  format: auth type
                  nullable: false
                  enum:
                    - sms_auth
                    - email_auth
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/User'
  /service:
    post:
      summary: Create a service
      tags:
        - service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateServiceRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '403':
          description: Invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    get:
      summary: Get all services
      tags:
        - service
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Service'
  /service/{service_id}:
    post:
      summary: Update a service
      tags:
        - service
      parameters:
        - in: path
          name: 'service_id'
          schema:
            type: integer
            format: uuid
          required: true
          allowEmptyValue: false
          description: Service identifier
      requestBody:
        description: Include values in the request body to update them
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
  '/service/{service_id}/template':
    get:
      summary: Get all templates for a service
      tags:
        - template
      parameters:
        - in: path
          name: 'service_id'
          schema:
            type: integer
            format: uuid
          required: true
          allowEmptyValue: false
          description: Service identifier
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Template'
    post:
      summary: Create a template for a service
      tags:
        - template
      parameters:
        - in: path
          name: 'service_id'
          schema:
            type: integer
            format: uuid
          required: true
          allowEmptyValue: false
          description: Service identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/CreateTemplateRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
  '/service/{service_id}/template/{template_id}':
    get:
      summary: Get a template for a service
      tags:
        - template
      parameters:
        - in: path
          name: 'service_id'
          schema:
            type: integer
            format: uuid
          required: true
          allowEmptyValue: false
          description: Service identifier
        - in: path
          name: 'template_id'
          schema:
            type: integer
            format: uuid
          required: true
          allowEmptyValue: false
          description: Template identifier
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
    post:
      summary: Update a template
      tags:
        - template
      parameters:
        - in: path
          name: 'service_id'
          schema:
            type: integer
            format: uuid
          required: true
          allowEmptyValue: false
          description: Service identifier
        - in: path
          name: 'template_id'
          schema:
            type: integer
            format: uuid
          required: true
          allowEmptyValue: false
          description: Template identifier to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTemplateRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
  /service/{service_id}/api-key:
    post:
      tags:
        - api key
      summary: Create API key for service
      parameters:
        - in: path
          name: service_id
          schema:
            type: string
            format: uuid
          required: true
          allowEmptyValue: false
          description: Service identifier
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                created_by:
                  description: User id who creates this key
                  type: string
                  format: uuid
                key_type:
                  type: string
                  enum:
                    - normal
                    - team
              required:
                - name
                - created_by
                - key_type
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                description: The API Key
                type: string
                format: uuid
                nullable: false
  /service/{service_id}/api-key/revoke/{api_key_id}:
    post:
      tags:
        - api key
      summary: Revoke API key
      parameters:
        - in: path
          name: service_id
          schema:
            type: string
            format: uuid
          required: true
          allowEmptyValue: false
          description: service identifier
        - in: path
          name: api_key_id
          schema:
            type: string
            format: uuid
          required: true
          allowEmptyValue: false
          description: API key identifier
      responses:
        202:
          description: OK
  /service/{service_id}/api-keys:
    get:
      tags:
        - api key
      summary: Get API keys for a service
      parameters:
        - in: path
          name: service_id
          schema:
            type: string
            format: uuid
          required: true
          allowEmptyValue: false
          description: service identifier
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  apiKeys:
                    type: array
                    items:
                      $ref: '#/components/schemas/APIKey'
  /service/{service_id}/api-keys/{key_id}:
    get:
      tags:
        - api key
      summary: Get a specific API key for a service
      parameters:
        - in: path
          name: service_id
          schema:
            type: string
            format: uuid
          required: true
          allowEmptyValue: false
          description: Service identifier
        - in: path
          name: key_id
          schema:
            type: string
            format: uuid
          required: true
          allowEmptyValue: false
          description: API key identifier
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  apiKeys:
                    type: array
                    items:
                      $ref: '#/components/schemas/APIKey'
  /v2/notifications/{notification_type}:
    post:
      summary: Send a notification
      security:
        - notifyAuth: []
      tags:
        - notification
      parameters:
        - in: path
          name: 'notification_type'
          schema:
            type: string
            enum:
              - sms
              - email
          required: true
          allowEmptyValue: false
          description: Type of notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/SMSNotificationRequest'
                - $ref: '#/components/schemas/EmailNotificationRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Notification'
                  - type: object
                    properties:
                      content:
                        type: object
                        properties:
                          body:
                            type: string
                          from_number:
                            type: string
                        required:
                          - body
                          - from_number
                    required:
                      - content
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/AuthErr'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                result: 'error'
                message: 'The requested URL was not found on the server. If you entered the URL manually please check
                your spelling and try again.'
        429:
          description: Exceeded rate or send limits
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V2ErrorMessage'
              example:
                errors:
                    - error: 'RateLimitError'
                      message: 'Exceeded rate limit for key type TYPE of LIMIT requests per INTERVAL seconds'
                status_code: 429
        500:
          $ref: '#/components/responses/InternalServerErr'
  /v2/notifications/{notification_id}:
    get:
      summary: Get notification
      security:
        - notifyAuth: []
      tags:
        - notification
      parameters:
        - in: path
          name: notification_id
          schema:
            type: string
            format: uuid
          required: true
          allowEmptyValue: false
          description: Notification identifier
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationWithStatus'
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/AuthErr'
        500:
          $ref: '#/components/responses/InternalServerErr'

components:
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/V2ErrorMessage'
          example:
            errors:
              - error: 'BadRequestError'
                message: 'sms_sender_id e925b547-8195-4ed2-83c5-0633a74d780a does not exist in database
                                  for service id 9ffb5212-e621-45df-820d-97ee65d392ab'
            status_code: 400
    AuthErr:
      description: Authentication Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/V2ErrorMessage'
          example:
            errors:
              - error: 'AuthError'
                message: 'Invalid token: service id is not the right data type'
            status_code: 403
    InternalServerErr:
      description: Internal server error
      content:
        application/json:
          schema:
            properties:
              result:
                type: string
                nullable: false
              message:
                type: string
                nullable: false
          example:
            result: 'error'
            message: 'Internal server error'
  schemas:
    V2ErrorMessage:
      description: Generic error message format for V2
      type: object
      properties:
        status_code:
          type: integer
          nullable: false
        errors:
          type: array
          items:
            type: object
            properties:
              error:
                type: string
              message:
                type: string
            required:
              - error
              - message
      required:
        - status_code
        - errors
    ErrorMessage:
      type: object
      properties:
        message:
          type: string
          nullable: false
        result:
          type: string
          nullable: false
        status_code:
          type: integer
          nullable: true
      required:
        - message
        - result
    Organisation:
      type: object
      properties:
        active:
          nullable: true
          type: boolean
        count_of_live_services:
          nullable: false
          type: integer
        domains:
          items:
            nullable: false
            type: string
          nullable: true
          type: array
        id:
          type: string
          nullable: false
          format: uuid
        name:
          nullable: false
          type: string
        organisation_type:
          enum:
            - other
          nullable: false
          type: string
    OrganisationResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/Organisation'
      properties:
        agreement_signed:
          format: datetime
          nullable: true
          type: string
        agreement_signed_at:
          format: datetime
          nullable: true
          type: string
        agreement_signed_by_id:
          format: uuid
          nullable: true
          type: string
        agreement_signed_on_behalf_of_email_address:
          nullable: true
          type: string
        agreement_signed_on_behalf_of_name:
          nullable: true
          type: string
        agreement_signed_version:
          nullable: false
          type: number
        crown:
          nullable: false
          type: boolean
        email_branding_id:
          format: uuid
          nullable: true
          type: string
        letter_branding_id:
          format: uuid
          nullable: true
          type: string
        request_to_go_live_notes:
          nullable: true
          type: string
    CreateUserRequest:
      type: object
      properties:
        name:
          type: string
          nullable: false
        password:
          type: string
          nullable: false
        email_address:
          type: string
          nullable: false
        mobile_number:
          type: string
          nullable: false
          example: "+19876543210"
        state:
          type: string
          nullable: false
        user_permissions:
          type: array
          nullable: false
          items:
            type: string
        auth_type:
          type: string
          format: auth type
          nullable: false
          enum:
            - sms_auth
            - email_auth
      required:
        - name
        - password
        - email_address
        - mobile_number
        - state
        - user_permissions
    User:
      type: object
      properties:
        additional_information:
          type: object
        auth_type:
          type: string
        blocked:
          type: boolean
        current_session_id:
          type: string
        email_address:
          type: string
        failed_login_count:
          type: integer
        id:
          type: string
        logged_in_at:
          type: string
        mobile_number:
          type: string
          example: "+19876543210"
        name:
          type: string
        organisations:
          type: array
          items:
            type: string
            format: uuid
        password_changed_at:
          type: string
          format: datetime
        permissions:
          type: object
          properties:
            uuid:
              type: array
              format: uuid
              items:
                type: string
                enum:
                  - manage_users
                  - manage_templates
                  - manage_settings
                  - send_texts
                  - send_emails
                  - send_letters
                  - manage_api_keys
                  - view_activity
        platform_admin:
          type: boolean
        services:
          type: array
          items:
            type: string
            format: uuid
        state:
          type: boolean
    CreateServiceRequest:
      type: object
      properties:
        active:
          type: boolean
          nullable: true
        created_by:
          type: string
          format: uuid
          nullable: false
        email_from:
          type: string
          format: email
          nullable: false
        message_limit:
          type: integer
          nullable: true
        name:
          type: string
          nullable: false
        organisation_id:
          type: string
          format: uuid
          nullable: true
        restricted:
          type: boolean
          nullable: false
        user_id:
          type: string
          format: uuid
          nullable: false
      required:
        - active
        - created_by
        - email_from
        - message_limit
        - name
        - organisation_id
        - restricted
        - user_id
    Service:
      type: object
      properties:
        active:
          type: boolean
          nullable: false
        all_template_folders:
          type: array
          items:
            type: string
        annual_billing:
          type: array
          items:
            type: string
            format: uuid
        consent_to_research:
          type: boolean
          nullable: true
        contact_link:
          type: string
          nullable: true
        count_as_live:
          type: boolean
          nullable: false
        created_by:
          type: string
          format: uuid
        crown:
          type: boolean
          nullable: true
        email_branding:
          type: string
          format: uuid
        email_from:
          type: string
          format: email
          nullable: false
        go_live_at:
          type: string
          format: datetime
          nullable: true
        go_live_user:
          type: string
          format: uuid
        id:
          type: string
          format: uuid
        inbound_api:
          type: array
          items:
            type: string
            format: url
        inbound_number:
          type: string
          format: uuid
        inbound_sms:
          type: array
          items:
            type: string
            format: uuid
        letter_branding:
          type: string
          format: uuid
        letter_contact_block:
          type: string
        letter_logo_filename:
          type: string
        message_limit:
          type: number
          nullable: false
        name:
          type: string
          nullable: false
        organisation:
          type: string
          format: uuid
        organisation_type:
          type: string
          nullable: true
          enum:
            - other
        permissions:
          type: array
          items:
            type: string
            enum:
              - international_sms
              - email
              - sms
              - inbound_sms
              - schedule_notifications
        prefix_sms:
          type: boolean
          nullable:  false
        rate_limit:
          type: number
          nullable: false
        research_mode:
          type: boolean
          nullable: false
        restricted:
          type: boolean
          nullable: false
        sending_domain:
          type: string
          nullable: true
        service_callback_api:
          type: array
          items:
            type: string
            format: uuid
        service_data_retention:
          type: array
          items:
            type: string
        smtp_user:
          type: string
          nullable: true
        users:
          type: array
          items:
            type: string
            format: uuid
        version:
          type: number
        volume_email:
          type: integer
          nullable: true
        volume_letter:
          type: integer
          nullable: true
        volume_sms:
          type: integer
          nullable: true
        whitelist:
          type: array
          items:
            properties:
              email_addresses:
                type: array
                items:
                  type: string
                  format: email
              phone_numbers:
                type: array
                items:
                  type: string
    CreateTemplateRequest:
      type: object
      nullable: false
      properties:
        content:
          type: string
          nullable: false
        created_by:
          type: string
          format: uuid
          nullable: false
        name:
          type: string
          nullable: false
        postage:
          type: string
          nullable: false
        process_type:
          type: string
          enum:
            - normal
            - priority
        service:
          type: string
          format: uuid
          nullable: false
        subject:
          type: string
          nullable: false
        template_type:
          type: string
          enum:
            - sms
            - email
            - letter
      required:
        - name
        - template_type
        - content
        - service
        - created_by
    Template:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateTemplateRequest'
      properties:
        archived:
          type: boolean
        created_at:
          type: string
          format: datetime
        folder:
          type: string
          format: uuid
        hidden:
          type: boolean
        id:
          type: string
          format: uuid
        redact_personalisation:
          type: boolean
        reply_to:
          type: string
          format: uuid
        reply_to_text:
          type: string
        service_letter_contact:
          type: string
          format: uuid
        template_redacted:
          type: string
          format: uuid
        updated_at:
          type: string
          format: datetime
        version:
          type: number
    NotificationRequest:
      type: object
      properties:
        reference:
          type: string
        template_id:
          type: string
          format: uuid
        personalisation:
          type: object
        scheduled_for:
          type: string
          format: datetime within next day
      required:
        - template_id
    SMSNotificationRequest:
      allOf:
        - $ref: '#/components/schemas/NotificationRequest'
        - type: object
          properties:
            sms_sender_id:
              type: string
              format: uuid
            phone_number:
              type: string
              format: phone_number
          required:
            - phone_number
    EmailNotificationRequest:
      allOf:
        - $ref: '#/components/schemas/NotificationRequest'
        - type: object
          properties:
            email_reply_to_id:
              type: string
              format: uuid
            email_address:
              type: string
              format: email_address
          required:
            - email_address
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        reference:
          type: string
        uri:
          type: string
          format: uri
        template:
          type: object
          properties:
            id:
              type: string
              format: uuid
            version:
              type: integer
            uri:
              type: string
              format: uri
          required:
            - id
            - version
            - uri
        scheduled_for:
          type: string
      required:
        - id
        - uri
        - template
    NotificationWithStatus:
      type: object
      properties:
        id:
          type: string
          format: uuid
          nullable: false
        body:
          type: string
          nullable: false
        completed_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
          nullable: false
        created_by_name:
          description: the user who requested for this notification
          type: string
          nullable: true
        email_address:
          type: string
          format: email
          nullable: true
        line_1:
          type: string
          nullable: true
        line_2:
          type: string
          nullable: true
        line_3:
          type: string
          nullable: true
        line_4:
          type: string
          nullable: true
        line_5:
          type: string
          nullable: true
        line_6:
          type: string
          nullable: true
        phone_number:
          type: string
          pattern: '^\+\d{9}$'
          nullable: true
          example:
            '+16502532222'
        postage:
          type: string
        postcode:
          type: string
          nullable: true
        reference:
          type: string
          nullable: true
        scheduled_for:
          type: string
          format: date-time
          nullable: true
        sent_at:
          type: string
          format: date-time
          nullable: true
        status:
          type: string
          nullable: false
          enum:
            - created
        subject:
          type: string
          nullable: true
        template:
          type: object
          properties:
            id:
              type: string
              format: uuid
              nullable: false
            uri:
              type: string
              nullable: false
            version:
              type: integer
              nullable: false
        type:
          type: string
          enum:
            - sms
            - email
          nullable: false
      required:
        - body
        - completed_at
        - created_at
        - created_by_name
        - email_address
        - id
        - line_1
        - line_2
        - line_3
        - line_4
        - line_5
        - line_6
        - phone_number
        - postage
        - postcode
        - reference
        - scheduled_for
        - sent_at
        - status
        - subject
        - template
    APIKey:
      type: object
      properties:
        created_at:
          type: string
          format: date-time
        created_by:
          type: string
          format: uuid
        expiry_date:
          type: string
          format: date-time
        id:
          type: string
          format: uuid
        key_type:
          type: string
          enum:
            - normal
            - team
        name:
          type: string
        updated_at:
          type: string
          format: date-time
        version:
          type: integer
  securitySchemes:
    adminAuth:
      description: "The admin user and secret are used to generate this authentication.  They are both defined as
                    configuration parameters"
      type: http
      scheme: bearer
      bearerFormat: JWT
    notifyAuth:
      description: "The format of this token is {key_name}-{iss-uuid}-{secret-key-uuid}.  When you
                    create API key you get the secret key in the response. This secret key should be used
                    to generate a bearer token to send notifications and enquire notification status. You can find
                    more at <a href='https://docs.notifications.service.gov.uk/rest-api.html#headers'>Authentication
                    headers</a>."
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - adminAuth: []